### ISSUE TITLE
some questions about setting

### ISSUE THREAD

**Issue by Grassyue** [AbdulMoqeet/HRAN#3]
Hi, thanks for your sharing.
I have some questions about the number of HRAB and global residual group, respectively.
How many HRABs cascaded in global residual group?
And how many global residual groups are stacked in BFF?
The figure in your paper is 3 HRABs consist of GR, and 4 GRs consist of BFF, is it correct ?

**Comment by AbdulMoqeet** [comment]
There are 4 GRs and 8 HRABs. To save space, we show 3 HRABs in the paper.

**Comment by Grassyue** [comment]
Thanks for your reply~
