### ISSUE TITLE
PSNR--SSIM

### ISSUE THREAD

**Issue by Auth0rM0rgan** [AbdulMoqeet/HRAN#5]
Hey @AbdulMoqeet, 

Thanks for sharing your code. I have a question about calculating PSNR and SSIM. How did you calculate the PSNR and SSIM? I couldn't find the code in your code and also I have tried the Matlab version to calculate them but the results are different. 

Thanks!

**Comment by AbdulMoqeet** [comment]
Hello, 

Could you please provide more details? If possible, please reach me on my email [amuqeet@khu.ac.kr](amuqeet@khu.ac.kr) with your results and training/testing environment.

**Comment by Auth0rM0rgan** [comment]
Hey @AbdulMoqeet,

**Comment by AbdulMoqeet** [comment]
Hello @Auth0rM0rgan ,

I have reverified my results on Set5 by just running the ``` demo.sh``` and they exactly match the paper's PSNR. 

If you could share more details, then I would be able to help. You can also reach me on email. 

```
Making model...

Evaluation:
100%|█████████████████████████████████████████████| 5/5 [00:06<00:00,  1.31s/it]
[Set5 x2]	PSNR: 38.207 (Best: 38.207 @epoch 1)
Forward: 6.94s

Saving...
Total: 7.14s

Making model...

Evaluation:
100%|█████████████████████████████████████████████| 5/5 [00:49<00:00,  9.92s/it]
[Set5 x2]	PSNR: 38.248 (Best: 38.248 @epoch 1)
Forward: 50.02s

Saving...
Total: 50.22s

Making model...

Evaluation:
100%|█████████████████████████████████████████████| 5/5 [00:07<00:00,  1.47s/it]
[Set5 x4]	PSNR: 32.435 (Best: 32.435 @epoch 1)
Forward: 7.77s

Saving...
Total: 8.02s

Making model...

Evaluation:
100%|█████████████████████████████████████████████| 5/5 [00:41<00:00,  8.26s/it]
[Set5 x4]	PSNR: 32.556 (Best: 32.556 @epoch 1)
Forward: 41.77s

Saving...
Total: 42.78s

Making model...

Evaluation:
100%|█████████████████████████████████████████████| 5/5 [00:05<00:00,  1.19s/it]
[Set5 x8]	PSNR: 27.108 (Best: 27.108 @epoch 1)
Forward: 6.38s

Saving...
Total: 6.65s

Making model...

Evaluation:
100%|█████████████████████████████████████████████| 5/5 [00:37<00:00,  7.57s/it]
[Set5 x8]	PSNR: 27.180 (Best: 27.180 @epoch 1)
Forward: 38.22s

Saving...
Total: 38.50s
```

**Comment by Auth0rM0rgan** [comment]
@AbdulMoqeet,

Thanks for the clarification but the way you are calculating the PSNR and SSIM is not FAIR at all. As mentioned in the EDSR repo they calculated the PSNR and SSIM with the Maltab script which is different from `calc_psnr` func in their repo and they reported their results based on the Matlab script of calculating PSNR and SSIM not the `calc_psnr` function in their repo! using the `calc_psnr` function leads to a higher PSNR number. By comparing the coefficient in `calc_psnr` and the Matlab script, you will see what is the difference.

Best

**Comment by AbdulMoqeet** [comment]
@Auth0rM0rgan 

The issue was related to the performance of my paper, and I have provided that. So, it will remain closed. 

Lastly, the results were generated through Matlab. The demo was given to quickly regenerate the results with similar accuracy.
